image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  REGISTRY: quay.io
  IMAGE_NAME: elasticsearch-container
  REGISTRY_USER: samsung_cnct
  ROBOT_ACCOUNT: elasticsearch_container_rw

stages:
  - build
  - test
  - publish

build-branch:
  variables:
    IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
  stage: build
  only:
    - branches
  except:
    - master
  script:
  - docker build -t $IMAGE_DEVL_NAME .
  - docker push $IMAGE_DEVL_NAME

build-master:
  stage: build
  only:
    - master
    - tags
  script:
  - docker build -t $IMAGE_PROD_NAME .
  - docker push $IMAGE_PROD_NAME

# Tests go here!
# test:
#    stage: test

publish-master:
  stage: publish
  only:
    - master
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${REGISTRY} -u ${REGISTRY_USER}+${ROBOT_ACCOUNT} -p ${REGISTRY_PASSWORD}
  # Any merge to master (i.e. a successful CI pass) will be tagged and pushed as latest
  - docker tag ${IMAGE_PROD_NAME} ${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}:latest
  - docker push ${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}:latest

publish-version-tag:
  stage: publish
  only:
    - /v[0-9]+\.[0-9]+(\.[0-9]+[a-z]?)?/
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${REGISTRY} -u ${REGISTRY_USER}+${ROBOT_ACCOUNT} -p ${REGISTRY_PASSWORD}
  # A tag push to master will be pushed to Quay with that tag
  - docker tag ${IMAGE_PROD_NAME} ${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}:$CI_COMMIT_TAG
  - docker push ${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}:$CI_COMMIT_TAG